### ISSUE TITLE
RNDeviceInfo.getUniqueId is not a function

### ISSUE THREAD

**Issue by kefyru** [react-native-community/react-native-device-info#793]
react-native 0.60.5
react-native-device-info 3.1.1

this.devUniqueId = await DeviceInfo.getUniqueId();
--->
Possible Unhandled Promise Rejection (id: 0):
TypeError: RNDeviceInfo.getUniqueId is not a function

in 2.3.2 was ok

**Comment by kefyru** [comment]
this.devUniqueId = DeviceInfo.getUniqueIdSync();
the same effect :(

**Comment by kefyru** [comment]
<img width="517" alt="Снимок экрана 2019-09-17 в 16 22 47" src="https://user-images.githubusercontent.com/29143718/65045670-e3e7f800-d967-11e9-8bd7-b01b10456fc5.png">

**Comment by LeanidHreska** [comment]
Hi, I have the same issue with `RNDeviceInfo.getDeviceId is not a function`.

```
react-native 0.60.5
react-native-device-info 3.1.1
```

Everything works with `2.3.2`

**Comment by kefyru** [comment]
console.log(NativeModules.RNDeviceInfo) returns the same info as i posted in last comment?

**Comment by mikehardy** [comment]
That is odd, it's definitely a function - https://github.com/react-native-community/react-native-device-info/blob/master/deviceinfo.js#L488

I prove it works in the example (which works for me in android and iOS) -> https://github.com/react-native-community/react-native-device-info/blob/master/example/App.js#L113

I suspect some sort of undefined state in your local project environment, which of course is easy to say but hard to prove. All I know is that I know for sure it works for me across 4 different machines (3 macs and one ubuntu machine).

In cases like these I recommend `npm install -g react-native-clean-project && react-native clean-project-auto` - I love that module for cases like these, as there are lots of caches most people are unaware of and that module gets everyone I've ever seen.

**Comment by Johan-dutoit** [comment]
For comparison, this is what my prod app returns for device info (using latest version)

![image](https://user-images.githubusercontent.com/1611055/65046852-48e82180-d959-11e9-8771-4416cbf46464.png)

**Comment by kefyru** [comment]
it's from DeviceInfo or from RNDeviceInfo?

**Comment by Johan-dutoit** [comment]
I copied it from your comment

> console.log(NativeModules.RNDeviceInfo) returns the same info as i posted in last comment?

p.s. I suggest you take a look at the `package.json` of `react-native-device-info` within your node modules folder.

**Comment by mikehardy** [comment]
@kefyru I believe that is a trivial difference, related only to what you named the local variable in your file when you do the javascript import

**Comment by kefyru** [comment]
> @kefyru I believe that is a trivial difference, related only to what you named the local variable in your file when you do the javascript import

no, if you see module, DeviceInfo calls RNDeviceInfo, for example:
https://github.com/react-native-community/react-native-device-info/blob/49e2b77e6051d1efcb93ce4d1fee1e9f78250f0f/deviceinfo.js#L350

**Comment by mikehardy** [comment]
Ah - got it! I still can't reproduce the problem locally though (sorry) - I'm literally building and testing a PR right now and it's just fine as per my previous comment. I'm sorry you're experiencing problems but without being able to reproduce there isn't much I can do. I suggest trying to clone our repo and build the example yourself, to prove it works (or reproduce conclusively that it does not)

**Comment by LeanidHreska** [comment]
> That is odd, it's definitely a function - https://github.com/react-native-community/react-native-device-info/blob/master/deviceinfo.js#L488
> 
> I prove it works in the example (which works for me in android and iOS) -> https://github.com/react-native-community/react-native-device-info/blob/master/example/App.js#L113
> 
> I suspect some sort of undefined state in your local project environment, which of course is easy to say but hard to prove. All I know is that I know for sure it works for me across 4 different machines (3 macs and one ubuntu machine).
> 
> In cases like these I recommend `npm install -g react-native-clean-project && react-native clean-project-auto` - I love that module for cases like these, as there are lots of caches most people are unaware of and that module gets everyone I've ever seen.


Thank you for your quick response! The package above helped me and now `getDeviceId` works for me.

**Comment by mikehardy** [comment]
Glad that helped. That module is a great find, I end up needing it maybe once a week! The best trick it has (in my opinion) is that it even gets Xcode DerivedData, that one bites a lot of people.

**Comment by MakhouT** [comment]
I am also having the same issue. I am on version 3.1.1 when using `DeviceInfo.getApplicationNameSync` it throws (also notice the name in inconsistent naming)
`RNDeviceInfo.getAppNameSync is not a function`

And yes I am importing it like so `import DeviceInfo from 'react-native-device-info';`

**Comment by mikehardy** [comment]
Yes, the internal APIs (from javascript to the native code) don't necessarily conform to the public module API. That is unimportant.

I'm sorry you are experiencing trouble but you haven't mentioned what steps you've taken to fix @MakhouT - I recommend react-native-clean-project as above

**Comment by ithustle** [comment]
> That is odd, it's definitely a function - https://github.com/react-native-community/react-native-device-info/blob/master/deviceinfo.js#L488
> 
> I prove it works in the example (which works for me in android and iOS) -> https://github.com/react-native-community/react-native-device-info/blob/master/example/App.js#L113
> 
> I suspect some sort of undefined state in your local project environment, which of course is easy to say but hard to prove. All I know is that I know for sure it works for me across 4 different machines (3 macs and one ubuntu machine).
> 
> In cases like these I recommend `npm install -g react-native-clean-project && react-native clean-project-auto` - I love that module for cases like these, as there are lots of caches most people are unaware of and that module gets everyone I've ever seen.

Same here. The above solutions doesn't work for me
`_reactNativeDeviceInfo.default.getUniqueID is not a function`

**Comment by mikehardy** [comment]
@ithustle you are having a separate issue, the public API did change to a consistent capitalization scheme, use getUniqueId (not lowercase d) per the migration guide in the wiki, other APIs moved as well

**Comment by ithustle** [comment]
@mikehardy, now I get it. Thanks.

**Comment by kefyru** [comment]
> That is odd, it's definitely a function - https://github.com/react-native-community/react-native-device-info/blob/master/deviceinfo.js#L488
> 
> I prove it works in the example (which works for me in android and iOS) -> https://github.com/react-native-community/react-native-device-info/blob/master/example/App.js#L113
> 
> I suspect some sort of undefined state in your local project environment, which of course is easy to say but hard to prove. All I know is that I know for sure it works for me across 4 different machines (3 macs and one ubuntu machine).
> 
> In cases like these I recommend `npm install -g react-native-clean-project && react-native clean-project-auto` - I love that module for cases like these, as there are lots of caches most people are unaware of and that module gets everyone I've ever seen.

You are monster )))
It helps me!
Thanks.

p.s. I couldn't use this tool (react-native-clean-project) because it uses yarn and can't clean project with npm (i had some errors), but i used terminal commands as describe there and it helped.

**Comment by mikehardy** [comment]
Actually the tool cleans both yarn and npm (and it does generate a couple ugly looking warnings but it keeps doing the work either way :-) ) - glad this worked out for everyone

**Comment by kristerkari** [comment]
> In cases like these I recommend `npm install -g react-native-clean-project && react-native clean-project-auto` - I love that module for cases like these, as there are lots of caches most people are unaware of and that module gets everyone I've ever seen.

This also worked for me, but it's a better idea not to install the global dependency, only run it with `npx react-native-clean-project`.

**Comment by mikehardy** [comment]
@kristerkari that is a very fair point, I hesitated myself before typing out that exact line. I just wanted to provide something that I was for sure worked and I didn't recall what exact command was connected as the main command for react-native-clean-project but I knew if I directed to clean-project-auto it would work.

If an `npx react-native-clean-project` runs clean-project-auto then yes, that's effective, and a better suggestion

**Comment by herstand** [comment]
Got the same error in the simulator after upgrading (in my case for the native `getApplicationName()` function), but only when building via the react native cli. Building via xcode always worked (but then I didn't have access to react native debug tools).

I'm trying `npx react-native-clean-project` with these settings:

![image](https://user-images.githubusercontent.com/950515/65258869-b0c17800-dad1-11e9-8863-82a9577b1b37.png)


Will follow-up once it completes.

**Comment by avenyproduction** [comment]
I am getting this problem with React-native version: 0.59.9. Tried: npx react-native-clean-project but it didn't help

**Comment by mikehardy** [comment]
Adding a postinstall that alters state on machines is pretty dangerous, and in my experience developers need to do this (something like react-native-clean-project) frequently for all sorts of reasons, so I'd be open to a note in the changelog - docs basically - but not code

**Comment by hopewise** [comment]
I am still having this issue, I tried all solutions above.. I am stuck on android, did not check iOS yet,, I tried forking the repo and use version 2, but I got an issue as here: https://stackoverflow.com/questions/58482748/why-a-sub-folder-is-not-downloaded-when-installing-the-package as all I need is to get rid of `UIWebView`  while I am still on react native 0.59.10

Any idea?

**Comment by mikehardy** [comment]
@hopewise you've gone down the wrong path unfortunately. I'm not sure what's wrong with your local state but it's corrupt. Your native code and javascript code is somehow not in sync. getUniqueId (not `getUniqueID` - note the capitalization) is definitely a function. `npx react-native-clean-project` perhaps

**Comment by ACoolmanBigHealth** [comment]
@MakhouT Despite what the docs say, there is no `getApplicationNameSync` in the code

**Comment by mikehardy** [comment]
@ACoolmanBigHealth that one was a popular "make it a constant" change, so getApplicationName is a constant and already sync now. The title of this issue is RNDeviceInfo.getUniqueId is not a function though, so I don't believe it's relevant?

**Comment by tauil** [comment]
> That is odd, it's definitely a function - https://github.com/react-native-community/react-native-device-info/blob/master/deviceinfo.js#L488
> 
> I prove it works in the example (which works for me in android and iOS) -> https://github.com/react-native-community/react-native-device-info/blob/master/example/App.js#L113
> 
> I suspect some sort of undefined state in your local project environment, which of course is easy to say but hard to prove. All I know is that I know for sure it works for me across 4 different machines (3 macs and one ubuntu machine).
> 
> In cases like these I recommend `npm install -g react-native-clean-project && react-native clean-project-auto` - I love that module for cases like these, as there are lots of caches most people are unaware of and that module gets everyone I've ever seen.

Just to state here that I had the same issue of the Promise not resolving. I was trying to use the `getFontScale` and it fixed by cleaning up my environment as @mikehardy suggested. I only did it after a colleague running the same project in a different environment get the Promise resolved.

**Comment by dorthwein** [comment]
Wanted to add a note here incase anyone goes to upgrade from an old version.  In previous versions the function was called `getUniqueID()` NOTE the capital ID at the end.  In current versions its `getUniqueId()` NOTE the lowercase Id....

**Comment by mikehardy** [comment]
@dorthwein an addendum to that is that if you are upgrading from a version that old you will want to scan the migration guides (linked at top of README) very carefully as there were quite a few changes like that - all easy but frustrating if they slow you down

**Comment by Mattimus333** [comment]
@dorthwein holy shit man, you are a lifesaver.
