### ISSUE TITLE
Android doesn't build after update to version 5.5.3

### ISSUE THREAD

**Issue by AlekseyKutsko** [react-native-community/react-native-device-info#974]
# Question

Hi! I Updated react-native-device-info from 2.1.2 to 5.5.3 and I have the error with build android.

```

> Task :react-native-device-info:compileDebugJavaWithJavac FAILED

Note: Recompile with -Xlint:unchecked for details.
/Users/beatdev/Documents/ReactNative/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java:8: error: package com.android.installreferrer.api does not exist
import com.android.installreferrer.api.InstallReferrerClient;
                                      ^
/Users/beatdev/Documents/ReactNative/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java:9: error: package com.android.installreferrer.api does not exist
import com.android.installreferrer.api.InstallReferrerStateListener;
                                      ^
/Users/beatdev/Documents/ReactNative/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java:10: error: package com.android.installreferrer.api does not exist
import com.android.installreferrer.api.ReferrerDetails;
                                      ^
/Users/beatdev/Documents/ReactNative/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java:15: error: cannot find symbol
  private InstallReferrerClient mReferrerClient;
          ^
  symbol:   class InstallReferrerClient
  location: class RNInstallReferrerClient
/Users/beatdev/Documents/ReactNative/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java:39: error: cannot find symbol
  private InstallReferrerStateListener installReferrerStateListener =
          ^
  symbol:   class InstallReferrerStateListener
  location: class RNInstallReferrerClient
/Users/beatdev/Documents/ReactNative/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java:19: error: cannot find symbol
    mReferrerClient = InstallReferrerClient.newBuilder(context).build();
                      ^
  symbol:   variable InstallReferrerClient
  location: class RNInstallReferrerClient
/Users/beatdev/Documents/ReactNative/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java:40: error: cannot find symbol
    new InstallReferrerStateListener() {
        ^
  symbol:   class InstallReferrerStateListener
  location: class RNInstallReferrerClient
Note: /Users/beatdev/Documents/ReactNative/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java uses or overrides a deprecated API.

```
My react-native and jetifier versions
```
"react-native": "0.61.5",
"jetifier": "1.6.4",
```

I removed `node_modules` and install again  and it didn't help.
I did `cd android && ./gradlew clean` and it didn't help.
I could not to find a similar issue. Any help?

**Comment by mikehardy** [comment]
That should not be happening, this line brings in the dependency: https://github.com/react-native-community/react-native-device-info/blob/85a04982d01ee7fef811bb255a8880714bb262a6/android/build.gradle#L51

And I don't reproduce the problem with local builds, nor has anyone else reported. Not saying there isn't something subtle wrong, or that there might be a need for documentation, but I think this will end up being something about your project (my first guess would be an unclean build - same as you were thinking with the gradle cleans). 🤔

**Comment by AlekseyKutsko** [comment]
Yes, you're right. My project has gulp task, which modifies react-native-device-info/android/build.gradle. I didn't know about this task. When I removed this task, build finished success. Sorry for you spent your time.

**Comment by mikehardy** [comment]
No problem and glad you found your root cause - build systems never fail to surprise :-)

**Comment by hblumberg** [comment]
We were seeing a similar issue [1] after upgrading to v7.0.2. It was a crash on launch rather than a build error.

We fixed it by adding `implementation "com.android.installreferrer:installreferrer:2.1"`, but I was surprised this was necessary given the [dependency](https://github.com/react-native-device-info/react-native-device-info/blob/ff6ebbbf00d691edb0c9787d76f26df4c3173963/android/build.gradle#L51) you referenced, @mikehardy. We do use `exclude module: 'react-native'`, but I didn't think that would cause issues.

We're not blocked on this, but curious if you have any thoughts. Thank you!

[1] (including for future searches)
```
E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: org.foo.android.debug, PID: 11091
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/installreferrer/api/InstallReferrerStateListener;
        at com.learnium.RNDeviceInfo.RNDeviceModule.<init>(RNDeviceModule.java:86)
        at com.learnium.RNDeviceInfo.RNDeviceInfo.createNativeModules(RNDeviceInfo.java:23)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1215)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1185)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1123)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:124)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:948)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.installreferrer.api.InstallReferrerStateListener" on path: DexPathList[[zip file "/data/app/org.foo.android.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/org.foo.android.debug-2/lib/arm64, /data/app/org.foo.android.debug-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.learnium.RNDeviceInfo.RNDeviceModule.<init>(RNDeviceModule.java:86) 
        at com.learnium.RNDeviceInfo.RNDeviceInfo.createNativeModules(RNDeviceInfo.java:23) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1215) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1185) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1123) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:124) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:948) 
        at java.lang.Thread.run(Thread.java:761) 
```

**Comment by mikehardy** [comment]
that is relatively baffling, I don't have any off-the-cuff thoughts on it. Your exclude shouldn't factor / the dependency *should* work. :thinking:  :shrug: :weary:
